language: node_js
node_js:
- "10"

before_install:
- npm install -g ionic cordova
- echo "Before Install Step"

install:
- echo "Install Step"
- npm install -g ionic cordova
- npm install

script:
- echo "Script Step"
- npm run lint

after_success:
- echo "After Success Step"

after_failure:
- echo "After failure Step"

before_deploy:
- echo "Before Deploy Step."

deploy:
- provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: www
