language: node_js
node_js:
- stable

before_install:
- npm install -g ionic cordova
- echo "Before Install Step"

install:
- echo "Install Step"
- npm install -g ionic cordova
- npm install

script:
- echo "Script Step"
- npm run lint
- rm -rf platforms
- ionic cordova platform add android
- ionic cordova build browser --prod --baseHref='/angular-client/'

after_success:
- echo "After Success Step"

after_failure:
- echo "After failure Step"

before_deploy:
- echo "Before Deploy Step."

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: www
